<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bplus</name>
   <tag></tag>
   <elementGuidId>dd34410d-188f-4a98-8ac4-280187f65b28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='headlessui-listbox-option-:r7:']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Bplus&quot;i] >> div >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>48f77d1e-b4af-46e4-a62d-3a3725073bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center space-x-2 </value>
      <webElementGuid>ea17ee1f-2930-44fb-b26a-b372b87c42ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bplus</value>
      <webElementGuid>cb8e2095-6336-44ee-a658-0ed47c66f3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-listbox-option-:r7:&quot;)/div[@class=&quot;flex items-center space-x-2&quot;]</value>
      <webElementGuid>7a98af57-e543-41db-a22a-028c7189f8d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='headlessui-listbox-option-:r7:']/div</value>
      <webElementGuid>27b67bd4-616c-4cc2-86d6-998da5e359d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Curvena'])[2]/following::div[1]</value>
      <webElementGuid>e62772fe-eb9a-4f2e-b673-daf5cb30bdb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Venusde'])[1]/following::div[3]</value>
      <webElementGuid>2ab58438-46e6-4a10-937f-67ac9dbfef0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Link'])[1]/preceding::div[2]</value>
      <webElementGuid>d88e4fbb-7eae-4fe4-9fe9-762361b1798a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div</value>
      <webElementGuid>c1c2f913-b607-4c24-8e46-af7191b705eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Bplus' or . = 'Bplus')]</value>
      <webElementGuid>4a72289d-5fe9-48d3-965e-982100d5fca7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
