<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Beaute Library</name>
   <tag></tag>
   <elementGuidId>c1a4679b-4f7b-4335-a78d-772293ff0705</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.font-normal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='headlessui-listbox-option-:r12:']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Beaute Library&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c387d90b-dd85-444c-82b1-c860f64a2818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-normal</value>
      <webElementGuid>d2c01b1b-c173-445d-a657-4838e0333875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beaute Library</value>
      <webElementGuid>67342532-b23f-4ca1-936f-6d1d34105ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-listbox-option-:r12:&quot;)/div[@class=&quot;flex items-center space-x-2&quot;]/div[@class=&quot;font-normal&quot;]</value>
      <webElementGuid>42c2523c-b1ae-4041-b5c4-169fe552599e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='headlessui-listbox-option-:r12:']/div/div</value>
      <webElementGuid>c6f1c4ef-2d4c-4056-94e7-204dba144c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select...'])[1]/following::div[5]</value>
      <webElementGuid>0a264120-2f8c-4dae-9508-f86af3174d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[1]/following::div[7]</value>
      <webElementGuid>b14a702c-159d-4706-98f9-752ae7c89790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Venusde'])[1]/preceding::div[1]</value>
      <webElementGuid>0b2f6b69-a060-4f4b-807a-f4387669339e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Curvena'])[1]/preceding::div[3]</value>
      <webElementGuid>e5de0d13-ee4a-4c50-b609-b3ab54528cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beaute Library']/parent::*</value>
      <webElementGuid>4917405c-ce15-4a6c-b697-c6d9544dbc20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div</value>
      <webElementGuid>2a752c2e-b157-4237-b572-5e7e68c017ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Beaute Library' or . = 'Beaute Library')]</value>
      <webElementGuid>8f107197-e47b-4f58-ad5a-2a4f8c80f4bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='headlessui-listbox-option-:r12:']/div</value>
      <webElementGuid>c0250940-e74c-4121-904a-4e287f6aa18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select...'])[1]/following::div[4]</value>
      <webElementGuid>c266e3aa-31ad-4f93-b1c1-1fbb0e51dda1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[1]/following::div[6]</value>
      <webElementGuid>ecd1411a-e04c-4f0d-b398-798cc068a7bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Venusde'])[1]/preceding::div[2]</value>
      <webElementGuid>f3d4e91b-8353-438e-8b65-46aad832a1ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div</value>
      <webElementGuid>238caef8-55bb-44a2-8a47-f4bb60c912af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
