<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Curvena</name>
   <tag></tag>
   <elementGuidId>1bfda196-1814-418f-8e88-7c7b14d035d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.inline-flex.w-full.items-center.space-x-2.truncate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-listbox-button-:r2:']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Brand&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>315c4120-970b-4054-bb4d-3070b5aa3fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Curvena</value>
      <webElementGuid>6ffc3a97-5919-4998-801a-79bc4c419100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-listbox-button-:r2:&quot;)/span[@class=&quot;inline-flex w-full items-center space-x-2 truncate&quot;]</value>
      <webElementGuid>26b062f2-9f2a-463f-ab34-93d18ebcfb38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex w-full items-center space-x-2 truncate</value>
      <webElementGuid>52dba2b2-c993-4fe7-927b-eaff3dfa79b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='headlessui-listbox-button-:r2:']/span</value>
      <webElementGuid>a5a029e3-a385-4904-8cf4-27c10fd9e3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[1]/following::span[1]</value>
      <webElementGuid>7dffb8a5-e745-4e74-9d10-23d0162f811d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Type History'])[1]/following::span[1]</value>
      <webElementGuid>d28e28e6-d1c6-432f-8b27-953f50fa3eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Link'])[1]/preceding::span[3]</value>
      <webElementGuid>f359e2e6-9405-443a-8d9f-8434a0194d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div/div/div/div/button/span</value>
      <webElementGuid>5bf6d9af-89e0-47f2-a441-d02bce04d325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Curvena' or . = 'Curvena')]</value>
      <webElementGuid>77e61ab1-07e6-4914-bd42-5eb81ec15502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='headlessui-listbox-button-:r2:']/span/div/span</value>
      <webElementGuid>ac883392-cbd5-4503-8342-e7f4ccaa99be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[1]/following::span[2]</value>
      <webElementGuid>f2768df5-9645-4b2a-add7-202e4a6af744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Type History'])[1]/following::span[2]</value>
      <webElementGuid>6ae26fda-463c-4adb-96ed-f9d8b4912299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Link'])[1]/preceding::span[2]</value>
      <webElementGuid>80692c56-a5d3-467d-925c-965e3176b280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::span[2]</value>
      <webElementGuid>f302c551-6c54-49dc-9a24-3349b2e132b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Curvena']/parent::*</value>
      <webElementGuid>54fd2975-573a-4aa1-815c-aecb755c420b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/span</value>
      <webElementGuid>2629afd9-44dc-413b-b55d-d7e4aa06b75f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
