<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Venusde</name>
   <tag></tag>
   <elementGuidId>c5795c0c-b73a-4e38-8a1e-4273657c261c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.inline-flex.w-full.items-center.space-x-2.truncate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-listbox-button-:r2:']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Brand&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fc4189f6-ab33-4ed6-bc7f-1175cbe7b1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex w-full items-center space-x-2 truncate</value>
      <webElementGuid>5a8a11aa-d847-4a27-8efe-90e0109d4558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Venusde</value>
      <webElementGuid>846ca0f4-5f9d-43fa-a986-594200738452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-listbox-button-:r2:&quot;)/span[@class=&quot;inline-flex w-full items-center space-x-2 truncate&quot;]</value>
      <webElementGuid>e1506de4-5c9d-4967-8f56-9de85bead6d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='headlessui-listbox-button-:r2:']/span</value>
      <webElementGuid>e90196a8-5fca-417d-b9c1-ebffde26b813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[1]/following::span[1]</value>
      <webElementGuid>c806f925-97e6-4df9-a0a4-3628f41d656f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Type History'])[1]/following::span[1]</value>
      <webElementGuid>90ef491c-925a-4907-8ea7-b8e624de8686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Link'])[1]/preceding::span[3]</value>
      <webElementGuid>bd92a732-f986-4d75-ac24-68accf393707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div/div/div/div/button/span</value>
      <webElementGuid>38e2f890-d3f3-45e1-81f7-13560ffe29f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Venusde' or . = 'Venusde')]</value>
      <webElementGuid>408d6f2f-d98c-4c94-86d2-097e440df0da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
