<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ticketing</name>
   <tag></tag>
   <elementGuidId>de7f7f68-ffda-48fc-a8a1-30b4bd062131</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.select-none > div:nth-of-type(9) > #admin-ticketing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='admin-ticketing'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Ticketing&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4b1054fb-9339-40be-9bc2-dce551a88a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>admin-ticketing</value>
      <webElementGuid>d2aa81b5-14bf-4dee-870a-48d35bc6f0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group mt-1 flex items-center justify-between truncate rounded-sm px-4 py-2 text-sm leading-5 transition duration-150 ease-in-out focus:outline-none text-sm space-x-5 px-4 text-slate-200 hover:bg-slate-800 focus:bg-slate-800 hover:text-white focus:text-gray-50</value>
      <webElementGuid>55c29b1b-fa23-46f7-ae73-9ee91586d240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-discover</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>08f6b677-21e9-4309-a873-9c2c8ed4a148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/ticketing</value>
      <webElementGuid>08a33388-a966-4e8b-b322-4f59c46aa904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ticketing</value>
      <webElementGuid>7de1c81d-eeb2-4f74-a1da-3ea26c27d8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;max-h-full min-h-screen max-w-full bg-white text-gray-800 dark:bg-slate-900 dark:text-white&quot;]/div[2]/div[@class=&quot;flex h-screen overflow-hidden bg-gray-100 text-gray-800&quot;]/div[@class=&quot;hidden overflow-x-hidden border-r border-theme-200 shadow-sm dark:border-r-0 dark:border-theme-800 dark:shadow-lg md:flex md:flex-shrink-0&quot;]/div[@class=&quot;flex w-64 flex-col&quot;]/div[@class=&quot;flex h-0 flex-1 flex-col bg-black shadow-md&quot;]/div[@class=&quot;flex flex-1 flex-col overflow-y-auto&quot;]/nav[@class=&quot;flex-1 select-none space-y-3 bg-gray-900 px-2 py-4&quot;]/div[2]/div[@class=&quot;hidden space-y-1 divide-y-2 divide-slate-800 sm:block&quot;]/div[@class=&quot;select-none&quot;]/div[9]/a[@id=&quot;admin-ticketing&quot;]</value>
      <webElementGuid>a4bf21ab-7fdb-413a-b12a-b0b86b53eef9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='admin-ticketing'])[2]</value>
      <webElementGuid>b8c3346b-cd2c-41af-ab73-bbc4f4337f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price List'])[2]/following::a[1]</value>
      <webElementGuid>49903668-663b-4335-be08-3988cd4c9c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payments'])[2]/following::a[2]</value>
      <webElementGuid>0fe57177-962c-47df-a26d-8ba82e4ec016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[2]/preceding::a[1]</value>
      <webElementGuid>976d6054-0b09-42b7-8f04-b519c91f0fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/admin/ticketing')])[2]</value>
      <webElementGuid>9f278761-c65a-4ca8-8b0a-fcce7cb6c0f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[9]/a</value>
      <webElementGuid>676dbdc8-012d-4c91-a68e-3a5347fc9f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'admin-ticketing' and @href = '/admin/ticketing' and (text() = 'Ticketing' or . = 'Ticketing')]</value>
      <webElementGuid>0a91daaf-339e-43e1-9e59-cb1faba2d400</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
